name: "Trobz - Open Source Projects"
description: "Open Source Solutions for the Enterprise | OpenERP Integration | Trobz"

url: "http://trobz.github.io/"


markdown: redcarpet
permalink: pretty

# github options
safe: true
lsi: false
pygments: true